# This file was generated by GoReleaser. DO NOT EDIT.
class Hkat < Formula
  desc "HookActions command line interface"
  homepage "https://github.com/hookactions/hkat-cli"
  version "0.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/hookactions/hkat-cli/releases/download/v0.1.1/hkat_0.1.1_Darwin_x86_64.tar.gz"
    sha256 "136dd44a1336245e09deba69eece28336f469f4712302ca1b0f56ec20889d728"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/hookactions/hkat-cli/releases/download/v0.1.1/hkat_0.1.1_Linux_x86_64.tar.gz"
      sha256 "1cb76879510dec44fba87ffd8bbe3a0f7b6258d76f8b443cc771317487049412"
    end
  end

  def install
    bin.install "hkat"
  end
end
